// ============================================================
// seed/seedDestinations.js
// Seeds the `destinations` table with rich metadata for the
// Phase 3 Recommendation Engine.
//
// Each destination has:
//   - Feature scores (0.0–1.0) for content-based matching
//   - Group-fit scores (family/couple/group/solo)
//   - Cost tiers (budget/standard/luxury daily per person)
//   - Seasonality (best months)
//   - Geo data (lat/long, nearest airport)
//
// Run with: node seed/seedDestinations.js
// ============================================================

require('dotenv').config();
const { prisma } = require('../src/db/client');

const destinations = [
  // ── GOA ──────────────────────────────────────────────────────
  {
    name: 'Goa',
    city: 'Panaji',
    state: 'Goa',
    country: 'India',
    region: 'West',
    latitude: 15.4909,
    longitude: 73.8278,
    averageTripCost: 25000,
    nearestAirport: 'GOI (Dabolim) / GOX (Mopa)',
    idealDaysMin: 3,
    idealDaysMax: 7,
    // Feature scores
    mountainScore: 0.0,
    beachScore: 0.95,
    climbingScore: 0.0,
    trekkingScore: 0.1,
    adventureScore: 0.5,
    nightlifeScore: 0.95,
    natureScore: 0.6,
    cultureScore: 0.4,
    foodScore: 0.85,
    relaxationScore: 0.8,
    spiritualScore: 0.15,
    // Group-fit
    familyScore: 0.6,
    coupleScore: 0.9,
    groupScore: 0.95,
    soloScore: 0.7,
    // Quality
    safetyScore: 0.75,
    popularityScore: 0.95,
    // Seasonality
    bestSeason: ['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar'],
    bestMonths: [10, 11, 12, 1, 2, 3],
    // Cost tiers
    budgetDailyCost: 1500,
    standardDailyCost: 3000,
    luxuryDailyCost: 7000,
    baseTransportCost: 4000,
    description: 'Sun-kissed beaches, vibrant nightlife, Portuguese heritage, and seafood paradise.',
    tags: ['beaches', 'nightlife', 'food', 'water_sports', 'relaxation', 'party']
  },

  // ── MANALI ───────────────────────────────────────────────────
  {
    name: 'Manali',
    city: 'Manali',
    state: 'Himachal Pradesh',
    country: 'India',
    region: 'North',
    latitude: 32.2396,
    longitude: 77.1887,
    averageTripCost: 20000,
    nearestAirport: 'KUU (Kullu-Manali)',
    idealDaysMin: 3,
    idealDaysMax: 6,
    mountainScore: 0.95,
    beachScore: 0.0,
    climbingScore: 0.7,
    trekkingScore: 0.85,
    adventureScore: 0.85,
    nightlifeScore: 0.2,
    natureScore: 0.9,
    cultureScore: 0.3,
    foodScore: 0.5,
    relaxationScore: 0.7,
    spiritualScore: 0.3,
    familyScore: 0.7,
    coupleScore: 0.85,
    groupScore: 0.9,
    soloScore: 0.8,
    safetyScore: 0.75,
    popularityScore: 0.9,
    bestSeason: ['Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
    bestMonths: [9, 10, 11, 12, 1, 2, 3, 4, 5, 6],
    budgetDailyCost: 1200,
    standardDailyCost: 2500,
    luxuryDailyCost: 6000,
    baseTransportCost: 3500,
    description: 'Picturesque valley, snow-capped peaks, Solang adventure, and tranquil mountain vibe.',
    tags: ['hills', 'adventure', 'snow', 'nature', 'relaxation', 'trekking', 'peace']
  },

  // ── KERALA (Munnar & Alleppey) ────────────────────────────────
  {
    name: 'Kerala',
    city: 'Kochi',
    state: 'Kerala',
    country: 'India',
    region: 'South',
    latitude: 10.8505,
    longitude: 76.2711,
    averageTripCost: 30000,
    nearestAirport: 'COK (Kochi)',
    idealDaysMin: 4,
    idealDaysMax: 8,
    mountainScore: 0.3,
    beachScore: 0.7,
    climbingScore: 0.1,
    trekkingScore: 0.4,
    adventureScore: 0.4,
    nightlifeScore: 0.15,
    natureScore: 0.95,
    cultureScore: 0.7,
    foodScore: 0.9,
    relaxationScore: 0.9,
    spiritualScore: 0.5,
    familyScore: 0.9,
    coupleScore: 0.9,
    groupScore: 0.6,
    soloScore: 0.7,
    safetyScore: 0.85,
    popularityScore: 0.85,
    bestSeason: ['Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar'],
    bestMonths: [9, 10, 11, 12, 1, 2, 3],
    budgetDailyCost: 1800,
    standardDailyCost: 3500,
    luxuryDailyCost: 8000,
    baseTransportCost: 5000,
    description: 'Serene backwaters, lush Munnar tea estates, houseboat cruises, and authentic cuisine.',
    tags: ['backwaters', 'nature', 'tea_gardens', 'relaxation', 'food', 'family', 'peace']
  },

  // ── ANDAMAN & NICOBAR ─────────────────────────────────────────
  {
    name: 'Andaman',
    city: 'Port Blair',
    state: 'Andaman & Nicobar',
    country: 'India',
    region: 'Islands',
    latitude: 11.7401,
    longitude: 92.6586,
    averageTripCost: 45000,
    nearestAirport: 'IXZ (Port Blair)',
    idealDaysMin: 5,
    idealDaysMax: 8,
    mountainScore: 0.0,
    beachScore: 0.95,
    climbingScore: 0.0,
    trekkingScore: 0.2,
    adventureScore: 0.7,
    nightlifeScore: 0.15,
    natureScore: 0.9,
    cultureScore: 0.3,
    foodScore: 0.6,
    relaxationScore: 0.9,
    spiritualScore: 0.1,
    familyScore: 0.7,
    coupleScore: 0.95,
    groupScore: 0.5,
    soloScore: 0.6,
    safetyScore: 0.8,
    popularityScore: 0.75,
    bestSeason: ['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr'],
    bestMonths: [10, 11, 12, 1, 2, 3, 4],
    budgetDailyCost: 2500,
    standardDailyCost: 4500,
    luxuryDailyCost: 10000,
    baseTransportCost: 9000,
    description: 'Pristine Radhanagar beach, crystal clear waters, scuba diving, and tropical escape.',
    tags: ['beaches', 'scuba', 'water_sports', 'relaxation', 'nature', 'honeymoon']
  },

  // ── PONDICHERRY ───────────────────────────────────────────────
  {
    name: 'Pondicherry',
    city: 'Pondicherry',
    state: 'Puducherry',
    country: 'India',
    region: 'South',
    latitude: 11.9416,
    longitude: 79.8083,
    averageTripCost: 15000,
    nearestAirport: 'MAA (Chennai) / PNY',
    idealDaysMin: 2,
    idealDaysMax: 4,
    mountainScore: 0.0,
    beachScore: 0.7,
    climbingScore: 0.0,
    trekkingScore: 0.05,
    adventureScore: 0.2,
    nightlifeScore: 0.5,
    natureScore: 0.5,
    cultureScore: 0.8,
    foodScore: 0.85,
    relaxationScore: 0.85,
    spiritualScore: 0.6,
    familyScore: 0.6,
    coupleScore: 0.9,
    groupScore: 0.7,
    soloScore: 0.85,
    safetyScore: 0.85,
    popularityScore: 0.7,
    bestSeason: ['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar'],
    bestMonths: [10, 11, 12, 1, 2, 3],
    budgetDailyCost: 1200,
    standardDailyCost: 2500,
    luxuryDailyCost: 5500,
    baseTransportCost: 3000,
    description: 'French Quarter charm, sea promenade, Auroville, quirky cafes, and quiet beaches.',
    tags: ['beaches', 'french_architecture', 'cafes', 'heritage', 'relaxation', 'food']
  },

  // ── GOKARNA ───────────────────────────────────────────────────
  {
    name: 'Gokarna',
    city: 'Gokarna',
    state: 'Karnataka',
    country: 'India',
    region: 'South',
    latitude: 14.5479,
    longitude: 74.3188,
    averageTripCost: 12000,
    nearestAirport: 'GOI (Goa) / Hubli',
    idealDaysMin: 3,
    idealDaysMax: 5,
    mountainScore: 0.0,
    beachScore: 0.85,
    climbingScore: 0.0,
    trekkingScore: 0.5,
    adventureScore: 0.3,
    nightlifeScore: 0.1,
    natureScore: 0.8,
    cultureScore: 0.3,
    foodScore: 0.5,
    relaxationScore: 0.95,
    spiritualScore: 0.4,
    familyScore: 0.4,
    coupleScore: 0.8,
    groupScore: 0.7,
    soloScore: 0.95,
    safetyScore: 0.75,
    popularityScore: 0.6,
    bestSeason: ['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar'],
    bestMonths: [10, 11, 12, 1, 2, 3],
    budgetDailyCost: 1000,
    standardDailyCost: 2000,
    luxuryDailyCost: 4500,
    baseTransportCost: 3500,
    description: 'Chill beach treks (Om Beach, Half Moon), laid-back shacks, and peaceful vibe.',
    tags: ['beaches', 'trekking', 'peace', 'budget_friendly', 'relaxation', 'nature']
  },

  // ── JAIPUR ────────────────────────────────────────────────────
  {
    name: 'Jaipur',
    city: 'Jaipur',
    state: 'Rajasthan',
    country: 'India',
    region: 'North-West',
    latitude: 26.9124,
    longitude: 75.7873,
    averageTripCost: 18000,
    nearestAirport: 'JAI (Jaipur)',
    idealDaysMin: 2,
    idealDaysMax: 4,
    mountainScore: 0.0,
    beachScore: 0.0,
    climbingScore: 0.0,
    trekkingScore: 0.1,
    adventureScore: 0.2,
    nightlifeScore: 0.3,
    natureScore: 0.2,
    cultureScore: 0.95,
    foodScore: 0.8,
    relaxationScore: 0.5,
    spiritualScore: 0.3,
    familyScore: 0.85,
    coupleScore: 0.8,
    groupScore: 0.8,
    soloScore: 0.7,
    safetyScore: 0.75,
    popularityScore: 0.9,
    bestSeason: ['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar'],
    bestMonths: [10, 11, 12, 1, 2, 3],
    budgetDailyCost: 1100,
    standardDailyCost: 2400,
    luxuryDailyCost: 6500,
    baseTransportCost: 2000,
    description: 'Grand Amber Fort, Hawa Mahal, royal palaces, street food, and rich Rajasthani culture.',
    tags: ['heritage', 'forts', 'culture', 'shopping', 'food', 'architecture']
  },

  // ── SHIMLA ────────────────────────────────────────────────────
  {
    name: 'Shimla',
    city: 'Shimla',
    state: 'Himachal Pradesh',
    country: 'India',
    region: 'North',
    latitude: 31.1048,
    longitude: 77.1734,
    averageTripCost: 16000,
    nearestAirport: 'SLV (Shimla) / IXC (Chandigarh)',
    idealDaysMin: 2,
    idealDaysMax: 4,
    mountainScore: 0.7,
    beachScore: 0.0,
    climbingScore: 0.2,
    trekkingScore: 0.5,
    adventureScore: 0.4,
    nightlifeScore: 0.2,
    natureScore: 0.8,
    cultureScore: 0.5,
    foodScore: 0.5,
    relaxationScore: 0.8,
    spiritualScore: 0.2,
    familyScore: 0.9,
    coupleScore: 0.8,
    groupScore: 0.7,
    soloScore: 0.6,
    safetyScore: 0.8,
    popularityScore: 0.8,
    bestSeason: ['Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
    bestMonths: [9, 10, 11, 12, 1, 2, 3, 4, 5, 6],
    budgetDailyCost: 1300,
    standardDailyCost: 2600,
    luxuryDailyCost: 5500,
    baseTransportCost: 2500,
    description: 'Mall Road, Jakhu temple, Ridge views, pine forests, and cool mountain air.',
    tags: ['hills', 'nature', 'colonial', 'family', 'snow', 'relaxation']
  },

  // ── UDAIPUR ───────────────────────────────────────────────────
  {
    name: 'Udaipur',
    city: 'Udaipur',
    state: 'Rajasthan',
    country: 'India',
    region: 'North-West',
    latitude: 24.5854,
    longitude: 73.7125,
    averageTripCost: 22000,
    nearestAirport: 'UDR (Udaipur)',
    idealDaysMin: 3,
    idealDaysMax: 5,
    mountainScore: 0.1,
    beachScore: 0.0,
    climbingScore: 0.0,
    trekkingScore: 0.15,
    adventureScore: 0.2,
    nightlifeScore: 0.3,
    natureScore: 0.6,
    cultureScore: 0.9,
    foodScore: 0.7,
    relaxationScore: 0.8,
    spiritualScore: 0.3,
    familyScore: 0.7,
    coupleScore: 0.95,
    groupScore: 0.6,
    soloScore: 0.7,
    safetyScore: 0.8,
    popularityScore: 0.85,
    bestSeason: ['Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar'],
    bestMonths: [9, 10, 11, 12, 1, 2, 3],
    budgetDailyCost: 1400,
    standardDailyCost: 3000,
    luxuryDailyCost: 8500,
    baseTransportCost: 3000,
    description: 'City of Lakes, royal boat cruises on Lake Pichola, stunning palaces, and romantic views.',
    tags: ['lakes', 'romance', 'heritage', 'palaces', 'culture', 'luxury']
  },

  // ── RISHIKESH ─────────────────────────────────────────────────
  {
    name: 'Rishikesh',
    city: 'Rishikesh',
    state: 'Uttarakhand',
    country: 'India',
    region: 'North',
    latitude: 30.0869,
    longitude: 78.2676,
    averageTripCost: 12000,
    nearestAirport: 'DED (Dehradun)',
    idealDaysMin: 2,
    idealDaysMax: 5,
    mountainScore: 0.5,
    beachScore: 0.0,
    climbingScore: 0.3,
    trekkingScore: 0.7,
    adventureScore: 0.9,
    nightlifeScore: 0.15,
    natureScore: 0.85,
    cultureScore: 0.5,
    foodScore: 0.6,
    relaxationScore: 0.6,
    spiritualScore: 0.95,
    familyScore: 0.5,
    coupleScore: 0.7,
    groupScore: 0.9,
    soloScore: 0.9,
    safetyScore: 0.75,
    popularityScore: 0.85,
    bestSeason: ['Sep', 'Oct', 'Nov', 'Dec', 'Feb', 'Mar', 'Apr', 'May'],
    bestMonths: [9, 10, 11, 12, 2, 3, 4, 5],
    budgetDailyCost: 900,
    standardDailyCost: 1800,
    luxuryDailyCost: 4500,
    baseTransportCost: 2000,
    description: 'Ganga rafting, bungee jumping, peaceful ghats, cafes, and spiritual energy.',
    tags: ['adventure', 'rafting', 'yoga', 'spirituality', 'nature', 'budget_friendly', 'peace']
  },

  // ── COORG (Madikeri) ──────────────────────────────────────────
  {
    name: 'Coorg',
    city: 'Madikeri',
    state: 'Karnataka',
    country: 'India',
    region: 'South',
    latitude: 12.4244,
    longitude: 75.7382,
    averageTripCost: 18000,
    nearestAirport: 'MYQ (Mysore) / IXE (Mangalore)',
    idealDaysMin: 3,
    idealDaysMax: 5,
    mountainScore: 0.5,
    beachScore: 0.0,
    climbingScore: 0.15,
    trekkingScore: 0.6,
    adventureScore: 0.35,
    nightlifeScore: 0.05,
    natureScore: 0.95,
    cultureScore: 0.4,
    foodScore: 0.65,
    relaxationScore: 0.9,
    spiritualScore: 0.2,
    familyScore: 0.8,
    coupleScore: 0.9,
    groupScore: 0.5,
    soloScore: 0.7,
    safetyScore: 0.8,
    popularityScore: 0.7,
    bestSeason: ['Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar'],
    bestMonths: [9, 10, 11, 12, 1, 2, 3],
    budgetDailyCost: 1300,
    standardDailyCost: 2700,
    luxuryDailyCost: 6000,
    baseTransportCost: 3000,
    description: 'Scotland of India, misty coffee plantations, waterfalls, and cozy homestays.',
    tags: ['coffee_estates', 'hills', 'nature', 'waterfalls', 'peace', 'relaxation']
  },

  // ── LADAKH (Leh) ──────────────────────────────────────────────
  {
    name: 'Ladakh',
    city: 'Leh',
    state: 'Ladakh',
    country: 'India',
    region: 'North',
    latitude: 34.1526,
    longitude: 77.5771,
    averageTripCost: 50000,
    nearestAirport: 'IXL (Leh)',
    idealDaysMin: 5,
    idealDaysMax: 9,
    mountainScore: 0.95,
    beachScore: 0.0,
    climbingScore: 0.6,
    trekkingScore: 0.9,
    adventureScore: 0.95,
    nightlifeScore: 0.05,
    natureScore: 0.9,
    cultureScore: 0.6,
    foodScore: 0.3,
    relaxationScore: 0.4,
    spiritualScore: 0.7,
    familyScore: 0.3,
    coupleScore: 0.7,
    groupScore: 0.85,
    soloScore: 0.9,
    safetyScore: 0.6,
    popularityScore: 0.85,
    bestSeason: ['May', 'Jun', 'Jul', 'Aug', 'Sep'],
    bestMonths: [5, 6, 7, 8, 9],
    budgetDailyCost: 2500,
    standardDailyCost: 4500,
    luxuryDailyCost: 9000,
    baseTransportCost: 8000,
    description: 'Pangong Tso lake, Nubra Valley, high passes, monasteries, and epic road trips.',
    tags: ['adventure', 'mountains', 'biking', 'lakes', 'monasteries', 'trekking']
  },

  // ── KASOL ─────────────────────────────────────────────────────
  {
    name: 'Kasol',
    city: 'Kasol',
    state: 'Himachal Pradesh',
    country: 'India',
    region: 'North',
    latitude: 32.0098,
    longitude: 77.3146,
    averageTripCost: 10000,
    nearestAirport: 'KUU (Kullu-Manali) / IXC (Chandigarh)',
    idealDaysMin: 2,
    idealDaysMax: 5,
    mountainScore: 0.85,
    beachScore: 0.0,
    climbingScore: 0.5,
    trekkingScore: 0.9,
    adventureScore: 0.7,
    nightlifeScore: 0.3,
    natureScore: 0.9,
    cultureScore: 0.3,
    foodScore: 0.6,
    relaxationScore: 0.7,
    spiritualScore: 0.3,
    familyScore: 0.3,
    coupleScore: 0.7,
    groupScore: 0.95,
    soloScore: 0.9,
    safetyScore: 0.6,
    popularityScore: 0.75,
    bestSeason: ['Mar', 'Apr', 'May', 'Jun', 'Sep', 'Oct', 'Nov'],
    bestMonths: [3, 4, 5, 6, 9, 10, 11],
    budgetDailyCost: 800,
    standardDailyCost: 1600,
    luxuryDailyCost: 3500,
    baseTransportCost: 3000,
    description: 'Mini Israel of India, Parvati Valley trekking, Kheerganga hot springs, and backpacker paradise.',
    tags: ['trekking', 'mountains', 'backpacking', 'nature', 'peace', 'budget_friendly']
  },

  // ── VARANASI ──────────────────────────────────────────────────
  {
    name: 'Varanasi',
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    country: 'India',
    region: 'North',
    latitude: 25.3176,
    longitude: 82.9739,
    averageTripCost: 12000,
    nearestAirport: 'VNS (Lal Bahadur Shastri)',
    idealDaysMin: 2,
    idealDaysMax: 4,
    mountainScore: 0.0,
    beachScore: 0.0,
    climbingScore: 0.0,
    trekkingScore: 0.0,
    adventureScore: 0.1,
    nightlifeScore: 0.1,
    natureScore: 0.3,
    cultureScore: 0.95,
    foodScore: 0.85,
    relaxationScore: 0.4,
    spiritualScore: 0.95,
    familyScore: 0.7,
    coupleScore: 0.5,
    groupScore: 0.6,
    soloScore: 0.85,
    safetyScore: 0.65,
    popularityScore: 0.85,
    bestSeason: ['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar'],
    bestMonths: [10, 11, 12, 1, 2, 3],
    budgetDailyCost: 800,
    standardDailyCost: 1800,
    luxuryDailyCost: 4500,
    baseTransportCost: 2500,
    description: 'Ancient ghats, Ganga Aarti, temple walks, and the spiritual heart of India.',
    tags: ['spirituality', 'culture', 'heritage', 'food', 'history', 'temples']
  },

  // ── DARJEELING ────────────────────────────────────────────────
  {
    name: 'Darjeeling',
    city: 'Darjeeling',
    state: 'West Bengal',
    country: 'India',
    region: 'East',
    latitude: 27.0360,
    longitude: 88.2627,
    averageTripCost: 15000,
    nearestAirport: 'IXB (Bagdogra)',
    idealDaysMin: 3,
    idealDaysMax: 5,
    mountainScore: 0.8,
    beachScore: 0.0,
    climbingScore: 0.3,
    trekkingScore: 0.6,
    adventureScore: 0.4,
    nightlifeScore: 0.1,
    natureScore: 0.9,
    cultureScore: 0.6,
    foodScore: 0.6,
    relaxationScore: 0.8,
    spiritualScore: 0.3,
    familyScore: 0.85,
    coupleScore: 0.8,
    groupScore: 0.6,
    soloScore: 0.7,
    safetyScore: 0.75,
    popularityScore: 0.75,
    bestSeason: ['Sep', 'Oct', 'Nov', 'Mar', 'Apr', 'May'],
    bestMonths: [9, 10, 11, 3, 4, 5],
    budgetDailyCost: 1100,
    standardDailyCost: 2200,
    luxuryDailyCost: 5000,
    baseTransportCost: 4000,
    description: 'Kanchenjunga views, toy train, tea estates, and colonial hill station charm.',
    tags: ['hills', 'tea_gardens', 'nature', 'colonial', 'family', 'peace']
  }
];

async function seed() {
  console.log('🌱 Seeding destinations table with Phase 3 metadata...\n');

  let created = 0;
  let updated = 0;
  let failed = 0;

  for (const dest of destinations) {
    try {
      await prisma.destination.upsert({
        where: {
          name_country: {
            name: dest.name,
            country: dest.country
          }
        },
        update: {
          ...dest
        },
        create: {
          ...dest
        }
      });
      const existing = await prisma.destination.findUnique({
        where: { name_country: { name: dest.name, country: dest.country } }
      });
      if (existing) {
        console.log(`  ✅ ${dest.name} (${dest.state}) — upserted`);
        created++;
      }
    } catch (err) {
      console.error(`  ❌ Failed: ${dest.name} — ${err.message}`);
      failed++;
    }
  }

  console.log(`\n📊 Done. Upserted: ${created}, Failed: ${failed}`);
  console.log(`📍 Total destinations in DB: ${await prisma.destination.count()}`);
}

seed()
  .catch((err) => {
    console.error('Seed failed:', err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
